import express from "express";
import http from "http";
import { WebSocketServer } from "ws";
import { nanoid } from "nanoid";

const app = express();
app.use(express.json());

const PORT = process.env.PORT || 10000;

// Required env on Render
// Example: https://your-service.onrender.com
const PUBLIC_BASE_URL = process.env.PUBLIC_BASE_URL;
if (!PUBLIC_BASE_URL) {
  console.error("Missing env PUBLIC_BASE_URL (e.g. https://your-service.onrender.com)");
  process.exit(1);
}

const SPOTIFY_AUTHORIZE_URL = "https://accounts.spotify.com/authorize";
const SPOTIFY_API_BASE = "https://api.spotify.com";

// In-memory sessions (good enough for single-user dev; use Redis for multi-user/prod)
const sessions = new Map(); // sessionId -> { ws, accessToken, expiresAt, localBase, scopes, lastPlayerHash }

// Helpers
function b64urlEncode(obj) {
  return Buffer.from(JSON.stringify(obj)).toString("base64url");
}
function b64urlDecode(str) {
  return JSON.parse(Buffer.from(str, "base64url").toString("utf8"));
}
function nowMs() { return Date.now(); }

function buildAuthorizeUrl({ clientId, redirectUri, scope, state }) {
  const u = new URL(SPOTIFY_AUTHORIZE_URL);
  u.searchParams.set("response_type", "code");
  u.searchParams.set("client_id", clientId);
  u.searchParams.set("redirect_uri", redirectUri);
  u.searchParams.set("scope", scope);
  u.searchParams.set("state", state);
  u.searchParams.set("show_dialog", "false");
  return u.toString();
}

/**
 * GET /oauth/start
 * Query:
 *  - client_id
 *  - scope (space-separated)
 *  - state_b64 (opaque blob generated by local server; must include sessionId & localCallback)
 *
 * Redirects user to Spotify authorize endpoint.
 */
app.get("/oauth/start", (req, res) => {
  const clientId = req.query.client_id;
  const scope = req.query.scope || "";
  const stateB64 = req.query.state_b64;

  if (!clientId || !stateB64) {
    return res.status(400).send("Missing client_id or state_b64");
  }

  const redirectUri = `${PUBLIC_BASE_URL}/oauth/callback`;

  const authorizeUrl = buildAuthorizeUrl({
    clientId,
    redirectUri,
    scope,
    state: stateB64
  });

  res.redirect(authorizeUrl);
});

/**
 * GET /oauth/callback
 * Spotify redirects here with ?code=...&state=...
 * We DO NOT exchange the code for tokens here (no client secret on Render).
 * We just redirect back to local with the code.
 */
app.get("/oauth/callback", (req, res) => {
  const { code, state, error } = req.query;
  if (error) return res.status(400).send(`Spotify auth error: ${error}`);
  if (!code || !state) return res.status(400).send("Missing code/state");

  let decoded;
  try {
    decoded = b64urlDecode(state);
  } catch {
    return res.status(400).send("Bad state");
  }

  const { sessionId, localCallback } = decoded;
  if (!sessionId || !localCallback) return res.status(400).send("State missing sessionId/localCallback");

  // Redirect back to local server with the auth code
  const u = new URL(localCallback);
  u.searchParams.set("code", code);
  u.searchParams.set("state_b64", state);
  res.redirect(u.toString());
});

/**
 * WebSocket: /ws
 * Local connects with ?sessionId=...
 * After connect, local sends JSON messages:
 *  {type:"tokens", access_token, expires_in}
 *  {type:"refreshed", access_token, expires_in}
 *
 * Middleware can request refresh:
 *  {type:"refresh_required"}
 * Middleware also emits playback updates:
 *  {type:"player_state", data: {...}}
 */
const server = http.createServer(app);
const wss = new WebSocketServer({ server, path: "/ws" });

wss.on("connection", (ws, req) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  const sessionId = url.searchParams.get("sessionId");

  if (!sessionId) {
    ws.close(1008, "Missing sessionId");
    return;
  }

  const session = sessions.get(sessionId) || {};
  session.ws = ws;
  sessions.set(sessionId, session);

  ws.on("message", (buf) => {
    let msg;
    try { msg = JSON.parse(buf.toString("utf8")); } catch { return; }

    if (msg.type === "tokens" || msg.type === "refreshed") {
      session.accessToken = msg.access_token;
      session.expiresAt = nowMs() + (Number(msg.expires_in || 3600) * 1000);
      sessions.set(sessionId, session);
    }
  });

  ws.on("close", () => {
    const s = sessions.get(sessionId);
    if (s) {
      s.ws = null;
      sessions.set(sessionId, s);
    }
  });
});

/**
 * Proxy endpoint: /spotify/*
 * Local calls this with headers:
 *  - x-session-id: <sessionId>
 * Middleware forwards to Spotify Web API with Authorization: Bearer <accessToken>
 */
app.all("/spotify/*", async (req, res) => {
  const sessionId = req.header("x-session-id");
  if (!sessionId) return res.status(401).json({ error: "Missing x-session-id" });

  const session = sessions.get(sessionId);
  if (!session?.accessToken) return res.status(401).json({ error: "No access token in session" });

  const path = req.originalUrl.replace(/^\/spotify/, "");
  const targetUrl = `${SPOTIFY_API_BASE}${path}`;

  // Collect raw body if present
  const chunks = [];
  req.on("data", (d) => chunks.push(d));
  req.on("end", async () => {
    const body = chunks.length ? Buffer.concat(chunks) : undefined;

    const headers = {
      "Authorization": `Bearer ${session.accessToken}`,
      // Forward relevant headers
      "Content-Type": req.header("content-type") || undefined
    };

    try {
      const r = await fetch(targetUrl, {
        method: req.method,
        headers,
        body: ["GET", "HEAD"].includes(req.method) ? undefined : body
      });

      // If token expired, ask local to refresh and return 401 so local can retry
      if (r.status === 401 && session.ws) {
        try { session.ws.send(JSON.stringify({ type: "refresh_required" })); } catch {}
      }

      const contentType = r.headers.get("content-type") || "";
      res.status(r.status);
      if (contentType) res.setHeader("content-type", contentType);

      const out = Buffer.from(await r.arrayBuffer());
      res.send(out);
    } catch (e) {
      res.status(502).json({ error: "Proxy failed", detail: String(e) });
    }
  });
});

/**
 * Poll playback state and push changes to local over WS.
 * This is the only way to approximate “state change forwarding” server-side.  [oai_citation:3‡Spotify for Developers](https://developer.spotify.com/documentation/web-api/reference/get-information-about-the-users-current-playback?utm_source=chatgpt.com)
 */
async function pollLoop() {
  for (const [sessionId, session] of sessions.entries()) {
    if (!session.accessToken || !session.ws) continue;

    try {
      const r = await fetch(`${SPOTIFY_API_BASE}/v1/me/player`, {
        headers: { "Authorization": `Bearer ${session.accessToken}` }
      });

      if (r.status === 204) continue; // No content (nothing playing)
      if (r.status === 401) {
        try { session.ws.send(JSON.stringify({ type: "refresh_required" })); } catch {}
        continue;
      }

      const data = await r.json();
      const hash = JSON.stringify({
        is_playing: data.is_playing,
        progress_ms: data.progress_ms,
        item_id: data?.item?.id,
        device_id: data?.device?.id,
        shuffle_state: data.shuffle_state,
        repeat_state: data.repeat_state
      });

      if (hash !== session.lastPlayerHash) {
        session.lastPlayerHash = hash;
        try {
          session.ws.send(JSON.stringify({ type: "player_state", data }));
        } catch {}
      }
    } catch {
      // ignore transient errors
    }
  }

  setTimeout(pollLoop, 1500); // 1.5s poll (adjust as needed)
}

pollLoop();

server.listen(PORT, () => {
  console.log(`Middleware listening on :${PORT}`);
});